// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Todo struct {
	ID         int64  `json:"id"`
	Message    string `json:"message"`
	IsFinished bool   `json:"is_finished"`
}
